name: "Ollama"
description: "Get up and running with large language models"
version: "latest"
slug: "ollama"
arch:
  - aarch64
  - amd64
url: https://ollama.com
environment:
  OLLAMA_MODELS: "/config/ollama"
  OLLAMA_KEEP_ALIVE: "-1" #This indicates to keep model loaded in memory.
map:
  - config:rw
image: docker.io/ollama/ollama
init: false
ingress: true
ingress_port: 11434
ingress_stream: true
ports:
  11434/tcp: 11434
ports_description:
  11434/tcp: "Ollama API"
startup: application
watchdog: tcp://[HOST]:[PORT:11434]
